spring:
  devtools:
    restart:
      enabled: true #false
    livereload:
      enabled: true #false
  security:
    user:
      password: 1
  datasource:
    url: jdbc:h2:tcp://localhost/~/codidb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
        show-sql: true #System.out.print로 출력한다.
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        SQL: debug #logger로 출력한다.
        type: trace #parameter 값 출력