
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('BOILING', '28', '100');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('HOT', '23', '27');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('WARM', '20', '22');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('NOTWARM', '17', '19');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('CRISP', '12', '16');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('COLD', '9', '11');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('COLDER', '5', '8');
INSERT INTO TEMPERATURE (TEMP_NAME, MIN_TEMP, MAX_TEMP) VALUES ('FREEZING', '-100', '4');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '패딩', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '두꺼운 코트', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '내복', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '목도리', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '장갑', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '기모', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '어그 부츠', 8);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '코트', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '울코트', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '플리스', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '누빔', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '두꺼운 니트', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '골덴', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '폴라티', 7);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '니트', 6);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '후드', 6);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '점퍼', 6);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '야상', 6);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '자켓', 6);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '가죽자켓', 6);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '맨투맨', 5);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '가디건', 5);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '트렌치코트', 5);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '청자켓', 5);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('FW', '바람막이', 5);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '긴팔 티셔츠', 4);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 긴팔 셔츠', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 자켓', 4);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 니트', 4);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 가디건', 4);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '면바지', 4);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '청바지', 4);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 긴팔 티셔츠', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반팔 티셔츠', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 긴팔 셔츠', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '얇은 블라우스', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '면바지', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '청바지', 3);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '샌들', 3);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반팔 티셔츠', 2);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반팔 셔츠', 2);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반바지', 2);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '샌들', 2);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '린넨', 1);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '민소매', 1);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반팔 티셔츠', 1);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반팔 셔츠', 1);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '반바지', 1);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '모자', 1);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, TEMP_ID) VALUES ('SS', '샌들', 1);