


INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('B', 'BOILING', 28);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('H', 'HOT', 23);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('W', 'WARM', 20);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('N', 'NOTWARM', 17);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('C1', 'CRISP', 12);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('C2', 'COLD', 9);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('C3', 'COLDER', 5);
INSERT INTO OUTFIT (OUTFIT_CODE, OUTFIT_NAME, TEMPERATURE) VALUES ('F', 'FREEZING', 4);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_1', '플리스', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_1', '가죽 재킷', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_1', '코트', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_2', '청바지', 7);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_3', '스카프', 7);

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_1', '니트', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_1', '내복', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_1', '롱패딩', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_2', '기모바지', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_3', '목도리', 8);
INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, OUTFIT_ID) VALUES ('WT_3', '털모자', 8);